version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          PG_HOST: 127.0.0.1
      - image: postgres:9.6
        environment:
          POSTGRES_DB: tikiarte_be_test
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Bundler Version
          command: bundle -v
      - run:
          name: Build gemfile
          command: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      - run:
          name: Setup DB
          command: bundle exec rails db:create db:schema:load --trace
      - run:
          name: Run test suite
          command: bundle exec rspec
      - run:
          name: Run Standard linter
          command: bundle exec standardrb

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME
          requires:
            - build
          filters:
            branches:
              only: main
