version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Run test suite
          command: bundle exec rspec
      - run:
          name: Run standard linter
          command: bundle exec standardrb

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git: https://git.heroku.com/tikiarte-be.git
          filters:
            branches:
              only: main
