version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Run test suite
          command: bundle exec rspec
      - run:
          name: Run standard linter
          command: bundle exec standardrb
