version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.7.2
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_DB: tikiarte_be_test
    executor: ruby/default
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Bundler Version
          command: bundle -v
      - run:
          name: Build gemfile
          command: bundle install
      - run:
          name: Database setup
          command: rails db:migrate
      - run:
          name: Run test suite
          command: bundle exec rspec
      - run:
          name: Run Standard linter
          command: bundle exec standardrb

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME
          requires:
            - build
          filters:
            branches:
              only: main
